### ISSUE TITLE
Support for product flavors

### ISSUE THREAD

**Issue by erd** [robolectric/robolectric-gradle-plugin#130]
Currently, we run tests against using the `debug` variant. This doesn't work correctly when the build has flavors.

**Comment by jaredsburrows** [comment]
@erd `Debug` is a `BuildType`. Do you mean `ProductFlavor` or `BuildType`? Currently I utilize product flavors in my apps. For instance, I usually run `gradlew testFreeDebug` to run `Robolectric` tests against the `ProductFlavor` "Free" and the `BuildType` "Debug".

**Comment by jhansche** [comment]
@jaredsburrows The description means that the current 1.0.0-SNAPSHOT version of the gradle plugin assumes **no** product flavors, as it tries to figure out the AndroidManifest, resources, and assets paths via the "debug" variant name. "Variant" is a matrix combination of `BuildType [+ ProductFlavors]`.  When there are *no* product flavors, the *variant* is simply "debug".  When there are, it is a combination of the build type and product flavor;  e.g., "debugFree" and "debugPaid".  That's what he means by "the `debug` variant" -- it was not a typo.  When you have product flavors, the current snapshot does not work, because the variant is not simply "debug" anymore.

See the discussion from #129: https://github.com/robolectric/robolectric-gradle-plugin/pull/129/files#diff-82b959b86a626f6171146a18ca9a224cR1

**Comment by jaredsburrows** [comment]
Alright, thanks for specifying `1.0.0-SNAPSHOT `.

**Comment by nenick** [comment]
You like to use robolectric with flavors? if you like try a solution without this plugin https://github.com/nenick/AndroidStudioAndRobolectric/tree/flavors
