### ISSUE TITLE
java.lang.UnsupportedOperationException: Robolectric does not support API level 1.

### ISSUE THREAD

**Issue by shawnlu123** [robolectric/robolectric-gradle-plugin#147]
Hi 

Method #1
For some reason, when I execute "testDebug" for all my test cases Robolectric gives me:
"java.lang.UnsupportedOperationException: Robolectric does not support API level 1" error.

Method #2
However, when I add "run config" and setup each individual test class in Android Studio, they pass without any problem.

Further information: I noticed that when I use Method #1, all the test cases are executed using "RobolectricTestRunner". When I use Method #2, they are executed using "RobolectricGradleTestRunner" which is the desired config. 
One last thing, I use "@RunWith(RobolectricGradleTestRunner.class)" annotation for all my test cases.

Any help is highly appreciated, thanks!

**Comment by erd** [comment]
If you're using AS 1.1.0 (which is recommended), you don't need to use this plugin. Please have a look at the the "Getting Started" docs here http://robolectric.org/getting-started/ or take a look at `robolectric/robolectric-samples` for a collection of working examples.

**Comment by rebornwhu** [comment]
Hi Erd

I took your advice and revert my build.gradle file. I've tried a couple of approaches and couldn't get it work. The symptom is the same:
1. When I run individual test class in AS, it works fine
2. When I use "gradle testDebug" to run all test cases, it always give me this "UnsupportedOperationException" error.

1. I made sure the "targetSDK" get defined in manifests of all my modules. 
2. It seems like "RobolectricGradleTestRunner" annotation never worked because in the stacktrace, the overridden within "RobolectricGradleTestRunner" never get called. 

Please share your thoughts, thanks!

**Comment by shawnlu123** [comment]
Hi Erd

I took your advice and revert my build.gradle file. I've tried a couple of approaches and couldn't get it work. The symptom is the same:
1. When I run individual test class in AS, it works fine
2. When I use "gradle testDebug" to run all test cases, it always give me this "UnsupportedOperationException" error.

I made sure the "targetSDK" get defined in manifests of all my modules.
It seems like "RobolectricGradleTestRunner" annotation never worked because in the stacktrace, the overridden within "RobolectricGradleTestRunner" never get called.
Please share your thoughts, thanks!
